#!/bin/sh
#
# @name Generic 10" Octo coaxial geometry
#
# @type Octorotor Coaxial
# @class Copter
#
# @output Motor1 motor 1
# @output Motor2 motor 2
# @output Motor3 motor 3
# @output Motor4 motor 4
# @output Motor5 motor 5
# @output Motor6 motor 6
# @output Motor7 motor 7
# @output Motor8 motor 8
#
# @maintainer Lorenz Meier <lorenz@px4.io>
#
# @board bitcraze_crazyflie exclude
#

. ${R}etc/init.d/rc.mc_defaults


param set MAV_TYPE 14

param set CA_ROTOR_COUNT 8

param set CA_ROTOR0_CT 15
param set CA_ROTOR0_PX 0.25
param set CA_ROTOR0_PY 0.22
param set CA_ROTOR0_PZ 0.02

param set CA_ROTOR1_CT 15
param set CA_ROTOR1_PX 0.25
param set CA_ROTOR1_PY -0.22
param set CA_ROTOR1_PZ 0.02
param set CA_ROTOR1_KM -0.05

param set CA_ROTOR2_CT 15
param set CA_ROTOR2_PX -0.25
param set CA_ROTOR2_PY -0.22
param set CA_ROTOR2_PZ 0.02

param set CA_ROTOR3_CT 15
param set CA_ROTOR3_PX -0.25
param set CA_ROTOR3_PY 0.22
param set CA_ROTOR3_PZ 0.02
param set CA_ROTOR3_KM -0.05

param set CA_ROTOR4_CT 15
param set CA_ROTOR4_PX 0.25
param set CA_ROTOR4_PY -0.22
param set CA_ROTOR4_PZ 0.11

param set CA_ROTOR5_CT 15
param set CA_ROTOR5_PX 0.25
param set CA_ROTOR5_PY 0.22
param set CA_ROTOR5_PZ 0.11
param set CA_ROTOR5_KM -0.05

param set CA_ROTOR6_CT 15
param set CA_ROTOR6_PX -0.25
param set CA_ROTOR6_PY 0.22
param set CA_ROTOR6_PZ 0.11

param set CA_ROTOR7_CT 15
param set CA_ROTOR7_PX -0.25
param set CA_ROTOR7_PY -0.22
param set CA_ROTOR7_PZ 0.11
param set CA_ROTOR7_KM -0.05

param set PWM_MAIN_FUNC1 101
param set PWM_MAIN_FUNC2 102
param set PWM_MAIN_FUNC3 103
param set PWM_MAIN_FUNC4 104
param set PWM_MAIN_FUNC5 105
param set PWM_MAIN_FUNC6 106
param set PWM_MAIN_FUNC7 107
param set PWM_MAIN_FUNC8 108

param set PWM_MAIN_MIN1 1100
param set PWM_MAIN_MIN2 1100
param set PWM_MAIN_MIN3 1100
param set PWM_MAIN_MIN4 1100
param set PWM_MAIN_MIN5 1100
param set PWM_MAIN_MIN6 1100
param set PWM_MAIN_MIN7 1100
param set PWM_MAIN_MIN8 1100

param set PWM_MAIN_MAX1 1900
param set PWM_MAIN_MAX2 1900
param set PWM_MAIN_MAX3 1900
param set PWM_MAIN_MAX4 1900
param set PWM_MAIN_MAX5 1900
param set PWM_MAIN_MAX6 1900
param set PWM_MAIN_MAX7 1900
param set PWM_MAIN_MAX8 1900

param set EFK2_OF_POS_X 0.167
param set EKF2_OF_POS_Y -0.017
param set EKF2_OF_POS_Z 0.06

param set EKF2_IMU_POS_X 0
param set EKF2_IMU_POS_Y 0
param set EKF2_IMU_POS_Z 0.01

param set EKF2_GPS_POS_X 0
param set EKF2_GPS_POS_Y -0.09
param set EKF2_GPS_POS_Z 0.01

param set EKF2_GPS_CTRL 7

param set COM_RCL_EXCEPT 7
param set NAV_RCL_ACT 1
param set COM_OBL_RC_ACT 5

param set MPC_TKO_RAMP_T 2

param set GPS_1_GNSS 63
param set GPS_1_PROTOCAL 6
param set MAN_ARM_GESTURE 0

param set MIS_DIST_1WP 10000

param set SDLOG_UTC_OFFSET 480

param set MAV_1_CONFIG 102

param set MAV_2_CONFIG 202
param set MAV_2_MODE 2

param set COM_FLTT_LOW_ACT 1
param set COM_QC_ACT 2

param set IMU_GYRO_FFT_EN 1
param set IMU_GYRO_DNF_EN 2
param set IMU_GYRO_FFT_MIN 30
param set IMU_GYRO_FFT_MAX 180
