#!/bin/sh
#
# @name Generic 10" Octo coaxial geometry
#
# @type Octorotor Coaxial
# @class Copter
#
# @output Motor1 motor 1
# @output Motor2 motor 2
# @output Motor3 motor 3
# @output Motor4 motor 4
# @output Motor5 motor 5
# @output Motor6 motor 6
# @output Motor7 motor 7
# @output Motor8 motor 8
#
# @maintainer Lorenz Meier <lorenz@px4.io>
#
# @board bitcraze_crazyflie exclude
#

. ${R}etc/init.d/rc.mc_defaults


param set-default MAV_TYPE 14

param set-default CA_ROTOR_COUNT 8
param set-default CA_ROTOR0_PX 0.35
param set-default CA_ROTOR0_PY 0.35
param set-default CA_ROTOR0_PZ -0.05
param set-default CA_ROTOR1_KM -0.05
param set-default CA_ROTOR1_PX 0.35
param set-default CA_ROTOR1_PY -0.35
param set-default CA_ROTOR1_PZ -0.05
param set-default CA_ROTOR2_PX -0.35
param set-default CA_ROTOR2_PY -0.35
param set-default CA_ROTOR2_PZ -0.05
param set-default CA_ROTOR3_PX -0.35
param set-default CA_ROTOR3_PY 0.35
param set-default CA_ROTOR3_PZ -0.05
param set-default CA_ROTOR3_KM -0.05
param set-default CA_ROTOR4_PX 0.35
param set-default CA_ROTOR4_PY -0.35
param set-default CA_ROTOR4_PZ 0.05
param set-default CA_ROTOR5_PX 0.35
param set-default CA_ROTOR5_PY 0.35
param set-default CA_ROTOR5_PZ 0.05
param set-default CA_ROTOR5_KM -0.05
param set-default CA_ROTOR6_PX -0.35
param set-default CA_ROTOR6_PY 0.35
param set-default CA_ROTOR6_PZ 0.05
param set-default CA_ROTOR7_KM -0.05
param set-default CA_ROTOR7_PX -0.35
param set-default CA_ROTOR7_PY -0.35
param set-default CA_ROTOR7_PZ 0.05

# 增加其他参数配置
param set-default BAT1_CAPACITY 10000
param set-default BAT1_N_CELLS 6
param set-default BAT1_R_INTERNAL 0.01
param set-default BAT1_V_DIV 18.565324
param set-default COM_FLTMODE1  1
param set-default COM_FLTMODE2 -1
param set-default COM_FLTMODE3 -1
param set-default COM_FLTMODE4  2
param set-default COM_FLTMODE5 -1
param set-default COM_FLTMODE6  2
param set-default EKF2_OF_CTRL 1
param set-default EKF2_OF_POS_X 0.167
param set-default EKF2_OF_POS_Y -0.017
param set-default EKF2_RNG_A_VMAX 2
param set-default GPS_1_GNSS 63
param set-default GPS_1_PROTOCOL 6
param set-default MAN_ARM_GESTURE 0
param set-default MAV_1_CONFIG 102 	# TELEM2
param set-default MAV_1_FORWARD 0
param set-default MAV_1_MODE 2

param set-default MC_PITCHRATE_MAX 70
param set-default MC_PITCHRATE_P 0.14
param set-default MC_ROLLRATE_MAX 70
param set-default MC_ROLLRATE_P 0.14
param set-default MC_YAWRATE_MAX 100
param set-default MIS_TAKEOFF_ALT 1
param set-default MPC_MAN_TILT_MAX 25
param set-default MPC_MAN_Y_MAX 100
param set-default MPC_TILTMAX_AIR 25
param set-default MPC_VELD_LP 4
param set-default MPC_XY_P 0.85
param set-default MPC_XY_VEL_D_ACC 0.15
param set-default MPC_XY_VEL_P_ACC 1.5
param set-default MPC_Z_V_AUTO_UP 2
param set-default RC_MAP_ARM_SW 6
param set-default RC_MAP_FLTMODE    5
param set-default RC_MAP_KILL_SW 7
param set-default SDLOG_PROFILE 19
param set-default SDLOG_UTC_OFFSET 480
param set-default SER_TEL1_BAUD 115200
param set-default SER_TEL2_BAUD 115200

param set-default PWM_MAIN_FUNC1 101
param set-default PWM_MAIN_FUNC2 102
param set-default PWM_MAIN_FUNC3 103
param set-default PWM_MAIN_FUNC4 104
param set-default PWM_MAIN_FUNC5 105
param set-default PWM_MAIN_FUNC6 106
param set-default PWM_MAIN_FUNC7 107
param set-default PWM_MAIN_FUNC8 108

# 设置解锁后电机以较低的转速预启动
param set-default PWM_MAIN_MIN1 1100
param set-default PWM_MAIN_MIN2 1100
param set-default PWM_MAIN_MIN3 1100
param set-default PWM_MAIN_MIN4 1100
param set-default PWM_MAIN_MIN5 1100
param set-default PWM_MAIN_MIN6 1100
param set-default PWM_MAIN_MIN7 1100
param set-default PWM_MAIN_MIN8 1100

param set-default PWM_MAIN_MAX1 1900
param set-default PWM_MAIN_MAX2 1900
param set-default PWM_MAIN_MAX3 1900
param set-default PWM_MAIN_MAX4 1900
param set-default PWM_MAIN_MAX5 1900
param set-default PWM_MAIN_MAX6 1900
param set-default PWM_MAIN_MAX7 1900
param set-default PWM_MAIN_MAX8 1900
