#!/bin/sh
#
# @name Generic Quadcopter
#
# @type Quadrotor x
# @class Copter
#
# @maintainer Lorenz Meier <lorenz@px4.io>
#

. ${R}etc/init.d/rc.mc_defaults

# Square quadrotor X PX4 numbering
#param set-default CA_ROTOR_COUNT 4
#param set-default CA_ROTOR0_PX 1
#param set-default CA_ROTOR0_PY 1
#param set-default CA_ROTOR1_PX -1
#param set-default CA_ROTOR1_PY -1
#param set-default CA_ROTOR2_PX 1
#param set-default CA_ROTOR2_PY -1
#param set-default CA_ROTOR2_KM -0.05
#param set-default CA_ROTOR3_PX -1
#param set-default CA_ROTOR3_PY 1
#param set-default CA_ROTOR3_KM -0.05

param set MAV_TYPE 2

param set CA_ROTOR_COUNT 4

param set CA_ROTOR0_CT 30
param set CA_ROTOR0_PX 0.24
param set CA_ROTOR0_PY 0.20
param set CA_ROTOR0_PZ 0.00

param set CA_ROTOR1_CT 30
param set CA_ROTOR1_PX -0.24
param set CA_ROTOR1_PY -0.20
param set CA_ROTOR1_PZ 0.00

param set CA_ROTOR2_CT 30
param set CA_ROTOR2_PX 0.24
param set CA_ROTOR2_PY -0.20
param set CA_ROTOR2_PZ 0.00
param set CA_ROTOR2_KM -0.05

param set CA_ROTOR3_CT 30
param set CA_ROTOR3_PX -0.24
param set CA_ROTOR3_PY 0.20
param set CA_ROTOR3_PZ 0.00
param set CA_ROTOR3_KM -0.05


param set PWM_MAIN_FUNC1 101
param set PWM_MAIN_FUNC2 102
param set PWM_MAIN_FUNC3 103
param set PWM_MAIN_FUNC4 104

param set PWM_MAIN_MIN1 1150
param set PWM_MAIN_MIN2 1150
param set PWM_MAIN_MIN3 1150
param set PWM_MAIN_MIN4 1150

param set PWM_MAIN_MAX1 1900
param set PWM_MAIN_MAX2 1900
param set PWM_MAIN_MAX3 1900
param set PWM_MAIN_MAX4 1900

param set EFK2_OF_POS_X 0.165
param set EKF2_OF_POS_Y 0.02
param set EKF2_OF_POS_Z 0.09

param set EKF2_IMU_POS_X 0.024
param set EKF2_IMU_POS_Y 0
param set EKF2_IMU_POS_Z -0.02

param set EKF2_GPS_POS_X 0
param set EKF2_GPS_POS_Y 0.03
param set EKF2_GPS_POS_Z -0.005

param set EKF2_GPS_CTRL 7

param set COM_RCL_EXCEPT 7
param set NAV_RCL_ACT 1
param set COM_OBL_RC_ACT 5

param set MPC_TKO_RAMP_T 2

param set GPS_1_GNSS 63
param set GPS_1_PROTOCAL 6
param set MAN_ARM_GESTURE 0

param set MIS_DIST_1WP 10000

param set SDLOG_UTC_OFFSET 480

param set MAV_1_CONFIG 102
param set MAV_1_MODE 0

param set MAV_2_CONFIG 202
param set MAV_2_MODE 2

param set COM_FLTT_LOW_ACT 1
param set COM_QC_ACT 2

param set EKF2_RNG_A_HMAX 5

param set SENS_IMU_MODE 1
param set EKF2_MULTI_IMU 1
param set CAL_ACC0_PRIO 25
param set CAL_ACC1_PRIO 100
param set CAL_GYRO0_PRIO 25
param set CAL_GYRO1_PRIO 100

#FLOW
param set SENS_FLOW_MINHGT 0.08
param set SENS_FLOW_MAXHGT 8
param set SENS_FLOW_MAXR 5
param set SENS_FLOW_RATE 20
param set SENS_FLOW_ROT 0
# END OF FLOW

param set MPC_TILTMAX_AIR 25

param set COM_RC_LOSS_T 1.0
param set NAV_ACC_RAD 15

param set RC_MAP_ROLL 1
param set RC_MAP_PITCH 2
param set RC_MAP_THROTTLE 3
param set RC_MAP_YAW 4

param set RC_MAP_FLTMODE 5
param set RC_MAP_ARM_SW 6
param set RC_KILL_SW 7

param set COM_FLTMODE1 1
param set COM_FLTMODE4 2
param set COM_FLTMODE6 2


param set EKF2_SEL_ERR_RED 0.2
param set EKF2_SEL_IMU_ACC 1.0
param set EKF2_SEL_IMU_ANG 15.0
param set EKF2_SEL_IMU_RAT 7.0
param set EKF2_SEL_IMU_VEL 2.0

param set MPC_ALT_MODE 0  #Altitude Following
param set COM_RC_IN_MODE 3
